### ISSUE TITLE
Hacking Request

### ISSUE THREAD

**Issue by Toaaster** [hackerxphantom/xinsta_brute#1]
Hi could you please hack my worst enemy in life his name is Elon Musk. Thanks. I will pay you handsomely with 5 Rubel. Plz do not hack me thanks!!!!! UwU >_<

**Comment by hackerxphantom** [comment]
Ok😂😂nice joke

**Comment by qrantz12** [comment]
https://www.instagram.com/btw_kiaan?igsh=MnQzejcxZTF6azkx

Hack this account and tell me the password
